Add scope video
Hacker0x01/docs.hackerone.com pull request #1027
Opened 2023-06-26 14:11 UTC by jessiwright

New video from Olivia
Also adding to asset inventory doc after discussion with Martijn

2023-06-27 14:36 UTC, martijnrusschen commented on docs/organizations/asset-inventory.md
> +<div style="position: relative; padding-bottom: 61.43344709897611%; height: 0;"><iframe src="https://www.loom.com/embed/d9b5fdf65c4c43e0b8f46bf9cabd39b3?sid=cc550dcf-9ff2-4918-8502-3b94b2363359" fram
Let's try to get a youtube video in here.

2023-06-29 14:22 UTC, jessiwright commented on docs/organizations/asset-inventory.md
> +<div style="position: relative; padding-bottom: 61.43344709897611%; height: 0;"><iframe src="https://www.loom.com/embed/d9b5fdf65c4c43e0b8f46bf9cabd39b3?sid=cc550dcf-9ff2-4918-8502-3b94b2363359" fram
New link added! @martijnrusschen

2023-06-29 14:45 UTC, danMateer commented on docs/organizations/defining-scope.md
> +<iframe width="560" height="315" src="https://www.youtube.com/embed/H2ZcSP04Vzw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyrosco
I don't have this running locally so it's worth gut-checking me on it. It should look like this:
![image](https://github.com/Hacker0x01/docs.hackerone.com/assets/34169713/adebf07b-2467-4b9b-ab75-e9351d22093b)

2023-06-29 15:08 UTC, martijnrusschen requested changes

2023-06-29 15:08 UTC, martijnrusschen commented on docs/organizations/defining-scope.md
> +<iframe width="560" height="315" src="https://www.youtube.com/embed/H2ZcSP04Vzw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyrosco
Yes, please use the old nocookie approach.

2023-06-29 15:55 UTC, martijnrusschen requested changes

2023-06-29 15:55 UTC, martijnrusschen commented on docs/organizations/asset-inventory.md
> +<iframe width="560" height="315" src="https://www.youtube.com/embed/H2ZcSP04Vzw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyrosco
Can we fix this one too to use the no cookie code?

2023-06-29 17:25 UTC, jessiwright reviewed
changes made

2023-06-29 17:26 UTC, martijnrusschen approved these changes

2023-06-29 18:39 UTC, merged