Bounty tables & calculator updates
Hacker0x01/docs.hackerone.com pull request #481
Opened 2021-09-17 17:41 UTC by jessiwright

Per request from Brian Reigersberg
3 pages updated
Reference document: https://docs.google.com/document/d/14yh-wGAdANRDcWvZyjmrTv6ZUqvPlt_NXYfXnGPOAHY/edit#

2021-09-22 07:45 UTC, Reigertje approved these changes

2021-09-22 07:52 UTC, Reigertje requested changes

2021-09-22 07:52 UTC, Reigertje commented on docs/programs/bounties.md
> +![suggesting bounties](./images/bounties-2.png)
This image shouldn't change

2021-09-22 07:52 UTC, Reigertje commented on docs/programs/bounties.md
> +![bounty calculator](./images/bounties-1.png)
I believe this should use the bounties-2 image 🙂

2021-09-23 07:53 UTC, Reigertje approved these changes

2021-09-23 07:58 UTC, saida approved these changes

2021-09-23 11:39 UTC, merged

2021-09-27 04:27 UTC, 1Elle1111 reviewed
Hi

2021-09-27 04:33 UTC, 1Elle1111 reviewed
Hi